spring:
  application:
    name: config-server-resouces
  config:
    activate:
      on-profile: default

alphabets:
  categoryRefID: 2
  category: Consonants
  total: 21
  values: b, c, d, e, f, g, h, j, k, l, m, n, p, q, r, s, t, v, w, x, y, z
  message: There are 21 Consonants in English